version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.0.0
  git-tools: sandbox/git-tools@0.3.0

jobs:
  deploy:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run:
          command: |
            echo "Dummy"
      - git-tools/prcomment:
          comment: "Test comment"

workflows:
  version: 2
  comment:
    jobs:
      - deploy
